travis:
  secure:
    BINSTAR_TOKEN: Hb7IdmOY4tsaYoNfIekRntuP3gqwAmgFdPebm2TLGmAFqRCOW2TXrshtmGdghCKTC6czIUklCzsvwc65UZoprQRzDFQa1dkpNIsi2HOYI5+lPFqUOmeHcH26a/Tp1jXq3GHNeypkPk+mHHazUOq/lm1ZYfz2na2JKMyBSMJ/kft5sLQPtdqYGlxgkg5vbCGZzxeUDDLOYmQB+N+w6n2MAsSlftb3VyRQo/kcbJ6rUgCf2ItFtqR0kWQ65kUC+f97x2sOeGjXBOkrffnE7P9UhgBtl2TYQGzerpd/1XdfaXXQe4VF6a4UUFJcl/i5M0phiHt7j1D6gINGWdIgiCU+OHkVkd8QDPYE+frGrX1AqKDN4O2ttkKC1O5FYgnDgy3xT+nQzIdUZWVkYcNEuKSnEYRkg239JWNsKjspEh+IdlCIVDYefKu2G6nPegHnaJVornBnhRKChm3GMK3EImgzw532ZOmWLbzO8mtapud5gDBkxyS8+pXE/olys3H3LXLhUYdUTCbjhikSdiy0ws9RpLusw2wWM6m9SgeBE8MJa/adhQpFeBzwIcD/iZzQgUauXVOopE+xooki3Q0dLkr8NnG66PGCJMrvwsN8Z/B3T4Be7hI7ACQFWTRWw8JQzfOm8tPpxopZb8Ej5aSR+Cd1Egs6nor+DkZdIaSX4dGrlLs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
