travis:
  secure:
    BINSTAR_TOKEN: ZUevqYPMv9o+sJF/xzB7U9nZQBkBEyEv5CYsa8HLaCHygymJyQEtjKOaLkz+a8DFuaCuGjuvzfw7WyQa9FKhA3lx+nPLZBeof8Aelnw5B0YhFUXenHkTpg40nRJ9LqKth361bRZ8RCGDqdylFu/9RaJvjzWkk4WTatuSAF2fEef23ajPw7NTcRB3Xb2kGEGwMq/OJe9YTSkqcST/AVMos6sjAymhr4sbyDNOO2uSrpvfythYnXpTTAT7D2+tgTb6d8wM1K8//f1euCCHYX9hB8xIV9CddFtJG8zv3tt6pdUE1YMA4+imteiPqHYWz7Js1D4SGd5mQqsLKBne+zwustPNMPbLchMjEHXxIHAxsbP+DSi10230XGVNofkDiXLYAsEglh3lYAZan6xIipCEL6WE9SIMqoVp6o9qNgmHqDso8m1dNaPEwrFePM6x/wkl2Sdj0xFfs7q5onH+7xfe9b3Yx4O0cIha7n0PbOuVV8pu/llyngjKNvEbVPgsI/j8c5YQDJ/jKXj0yx9WA0Exly5PD8H9XqscJ81pDgU3WC0+kxr4cUTspG/a3R5wf8ciF+XHTbG8r4aHtzolm0BpmBqxWwsb+at5hsTn4a6JmW8Uk3EUcvHR4QOQZWA2OfIisExeFJvJkX85DMA4jpE0QNYsLB93/SH2pHHycPOu0gE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
